<?php
/**
 * Language labels for plugin "addresses"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		'comment' => 'comment',
		'new_record' => 'New record',
		'preferences' => 'Preferences',
		'filters' => 'Filters',
		'found' => 'Found',
		'record' => 'record',
		'records' => 'records',
		'records_by_page' => 'Records by page',
		'choose_action' => 'Choose action',
		'export_csv' => 'Exporter sélection CSV',
		'export_xml' => 'Exporter sélection XML',
		'export_all_csv' => 'Exporter tous les enregistrements CSV',
		'export_all_xml' => 'Exporter tous les enregistrements XML',
		'delete_selected' => 'Delete selected',
		'gender' => 'gender',
		'firstname' => 'first name',
		'lastname' => 'last name',
		'middle_name' => 'middle name',
		'email' => 'email',
		'birthday' => 'birthday',
		'title' => 'title',
		'phone' => 'phone',
		'mobile' => 'mobile',
		'www' => 'www',
		'address' => 'address',
		'building' => 'building',
		'room' => 'room',
		'company' => 'company',
		'city' => 'city',
		'zip' => 'zip',
		'region' => 'region',
		'country' => 'country',
		'image' => 'image',
		'fax' => 'fax',
		'description' => 'description',
		'all' => 'all',
		'yes' => 'yes',
		'no' => 'no',
		'keywords' => 'keywords...',
		'' => '',
	),
	"fr" => Array (
		'comment' => 'commentaire',
		'new_record' => 'Nouvel enregistrement',
		'preferences' => 'Préférences',
		'filters' => 'filtres',
		'found' => 'Trouvé',
		'record' => 'enregistrement',
		'records' => 'enregistrements',
		'records_by_page' => 'Enregistrements par page',
		'choose_action' => 'Actions',
		'export_csv' => 'Exporter sélection CSV',
		'export_xml' => 'Exporter sélection XML',
		'export_all_csv' => 'Exporter tous les enregistrements CSV',
		'export_all_xml' => 'Exporter tous les enregistrements XML',
		'delete_selected' => 'Supprimer la sélection',
		'gender' => 'genre',
		'firstname' => 'prénom',
		'lastname' => 'nom',
		'middle_name' => 'middle name',
		'email' => 'email',
		'birthday' => 'anniversaire',
		'title' => 'titre',
		'phone' => 'téléphone',
		'mobile' => 'mobile',
		'www' => 'www',
		'address' => 'adresse',
		'building' => 'bâtiment',
		'room' => 'chambre',
		'company' => 'companie',
		'city' => 'ville',
		'zip' => 'nip',
		'region' => 'région',
		'country' => 'pays',
		'image' => 'image',
		'fax' => 'fax',
		'description' => 'description',
		'all' => 'tous',
		'yes' => 'oui',
		'no' => 'non',
		'keywords' => 'recherche...',
	),
);

?>